cfg_optim:
  max_epochs: 200
  patience: 10
  monitor_val: sdr
  lr: 0.001
  grad_clip_norm: 5
  loss_type: L1
  loss_domain: t+tf
  ngpus: null
  sync_bn: true
  accumulate_grad_batches: 1
cfg_scheduler:
  name: step
  gamma: 0.98
  step_size: 2
cfg_eval:
  device: cuda
  segment_len: 10.0
  overlap: 0.1
  hop_size: null
  verbose_per_track: true
  sdr_type: global
  win_dur: 1.0
  rec_dir: null
targets: vocals
sample_rate: 44100
n_fft: 2048
n_hop: 512
eps: 1.0e-07
target: vocals
time_layer: lstm
band_layer: lstm
feature_dim: 64
num_repeat: 8
n_att_head: 0
attn_enc_dim: 0
name: bsrnn
name_out_dir: bsrnn
name_tblog_dir: bsrnn
